# SPDX-FileCopyrightText: 2023 University of Manchester
#
# SPDX-License-Identifier: Apache-2.0

name: Package exporter

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: actions/setup-go@v4
    - run: pip install psutil requests
    - run: go build
    - run: VERSION=$(git describe --tags --always)
    - run: GOOS=$(go env GOOS)
    - run: GOARCH=$(go env GOARCH)
    - run: export ARTIFACT_NAME="prometheus-slurm-exporter-${VERSION}-${GOOS}_${GOARCH}"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./prometheus-slurm-exporter
