# SPDX-FileCopyrightText: 2023 University of Manchester
#
# SPDX-License-Identifier: Apache-2.0

name: Package exporter

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
    - uses: actions/setup-python@v3
    - uses: actions/setup-go@v4
    - run: pip install psutil requests
    - run: go build
    - run: |
        VERSION=$(git describe --tags --always)
        GOOS=$(go env GOOS)
        GOARCH=$(go env GOARCH)
        ARTIFACT_NAME="prometheus-slurm-exporter-${VERSION}-${GOOS}_${GOARCH}"
        cp -a ./prometheus-slurm-exporter $ARTIFACT_NAME
        echo "ARTIFACT_NAME=$(echo $ARTIFACT_NAME)" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./prometheus-slurm-exporter
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.ARTIFACT_NAME }}"
        allowUpdates: true

    # - uses: actions/create-release@v1
    #   id: create_release
    #   with:
    #     draft: false
    #     prerelease: false
    #     release_name: ${{ env.VERSION }}
    #     tag_name: ${{ github.ref }}
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    # - uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./prometheus-slurm-exporter
    #     asset_name: ${{ env.ARTIFACT_NAME }}
    #     asset_content_type: application/octet-stream
